spring:
  application:
    name: notification-service
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      auto-offset-reset: earliest
      group-id: notification-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring:
          json:
            trusted:
              package: "*"
            use:
              type:
                headers: false
            value:
              default:
                type:
                  java.util.HashMap

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: health, info