spring:
  application:
    name: post-service
  datasource:
    url: jdbc:mysql://localhost:3306/post_db?createDatabaseIfNotExist=true
    username:
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8082

aws:
  access-key:
  secret-key:
  region:
  s3:
    bucket-name:

management:
  endpoints:
    web:
      exposure:
        include: health, info