spring:
  application:
    name: search-service
  elasticsearch:
    uris: http://localhost:9200
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: search-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring:
          json:
            trusted:
              package: "*"
            use:
              type:
                headers: false
            value:
              default:
                type:
                  java.util.HashMap

server:
  port: 8084

management:
  endpoints:
    web:
      exposure:
        include: health, info

